export const seedData = {
  customers: [
    {
      name: "Rohan Malhotra",
      phone: "+91 98111 22110",
      email: "rohan.malhotra@example.com",
    },
    {
      name: "Anjali Gupta",
      phone: "+91 98200 98332",
      email: "anjali.gupta@example.com",
    },
    {
      name: "Imran Khan",
      phone: "+91 99105 55612",
      email: "imran.khan@example.com",
    },
    {
      name: "Priya Sharma",
      phone: "+91 97614 44281",
      email: "priya.sharma@example.com",
    },
    {
      name: "Vijay Patel",
      phone: "+91 98765 43210",
      email: "vijay.patel@example.com",
    },
  ],
  bookings: [
    {
      customerName: "Rohan Malhotra",
      eventDate: "2026-04-11",
      eventType: "Wedding",
      guests: 250,
      hall: "Royal Ballroom",
      status: "Confirmed",
    },
    {
      customerName: "Anjali Gupta",
      eventDate: "2026-04-15",
      eventType: "Engagement",
      guests: 120,
      hall: "Emerald Hall",
      status: "Pending",
    },
    {
      customerName: "Imran Khan",
      eventDate: "2026-04-20",
      eventType: "Corporate",
      guests: 80,
      hall: "Garden Pavilion",
      status: "Confirmed",
    },
    {
      customerName: "Priya Sharma",
      eventDate: "2026-04-25",
      eventType: "Birthday",
      guests: 100,
      hall: "Emerald Hall",
      status: "Pending",
    },
    {
      customerName: "Vijay Patel",
      eventDate: "2026-05-02",
      eventType: "Wedding",
      guests: 350,
      hall: "Royal Ballroom",
      status: "Confirmed",
    },
  ],
  payments: [
    {
      customerName: "Rohan Malhotra",
      totalAmount: 210000,
      paidAmount: 210000,
      remainingAmount: 0,
      status: "Paid",
      dueDate: "2026-04-05",
    },
    {
      customerName: "Anjali Gupta",
      totalAmount: 185000,
      paidAmount: 120000,
      remainingAmount: 65000,
      status: "Pending",
      dueDate: "2026-04-10",
    },
    {
      customerName: "Imran Khan",
      totalAmount: 150000,
      paidAmount: 75000,
      remainingAmount: 75000,
      status: "Pending",
      dueDate: "2026-04-15",
    },
    {
      customerName: "Priya Sharma",
      totalAmount: 125000,
      paidAmount: 125000,
      remainingAmount: 0,
      status: "Paid",
      dueDate: "2026-04-20",
    },
    {
      customerName: "Vijay Patel",
      totalAmount: 320000,
      paidAmount: 160000,
      remainingAmount: 160000,
      status: "Pending",
      dueDate: "2026-04-28",
    },
  ],
  reminders: [
    {
      type: "Event tomorrow",
      message: "Rohan Malhotra wedding event at Royal Ballroom - 250 guests expected",
      dueDate: "2026-04-10",
    },
    {
      type: "Payment due",
      message: "Anjali Gupta - Rs. 65,000 pending payment",
      dueDate: "2026-04-10",
    },
    {
      type: "Event tomorrow",
      message: "Imran Khan corporate event at Garden Pavilion - 80 guests",
      dueDate: "2026-04-19",
    },
    {
      type: "Payment due",
      message: "Vijay Patel - Rs. 160,000 payment due for wedding",
      dueDate: "2026-04-25",
    },
  ],
  foodPlans: [
    {
      customerName: "Rohan Malhotra",
      menuType: "Non-Veg",
      guests: 250,
      foodQuantity: "250 plates + 50 backup",
      eventDate: "2026-04-11",
    },
    {
      customerName: "Anjali Gupta",
      menuType: "Veg",
      guests: 120,
      foodQuantity: "120 plates + 24 backup",
      eventDate: "2026-04-15",
    },
    {
      customerName: "Imran Khan",
      menuType: "Non-Veg",
      guests: 80,
      foodQuantity: "80 plates + 16 backup",
      eventDate: "2026-04-20",
    },
    {
      customerName: "Priya Sharma",
      menuType: "Veg",
      guests: 100,
      foodQuantity: "100 plates + 20 backup",
      eventDate: "2026-04-25",
    },
  ],
  invoices: [
    {
      customerName: "Rohan Malhotra",
      eventDetails: "Wedding Reception - Royal Ballroom",
      amountBreakdown: "Hall: Rs. 1,20,000\nCatering: Rs. 70,000\nDecor: Rs. 20,000",
      totalAmount: 210000,
    },
    {
      customerName: "Anjali Gupta",
      eventDetails: "Engagement Party - Emerald Hall",
      amountBreakdown: "Hall: Rs. 80,000\nCatering: Rs. 55,000\nDecor: Rs. 50,000",
      totalAmount: 185000,
    },
    {
      customerName: "Imran Khan",
      eventDetails: "Corporate Event - Garden Pavilion",
      amountBreakdown: "Hall: Rs. 60,000\nCatering: Rs. 65,000\nSetup: Rs. 25,000",
      totalAmount: 150000,
    },
  ],
};
